//
// This file was auto-generated by a tool.  Do not modify.
//
using System.Resources;
using System.Reflection;

[assembly: NeutralResourcesLanguageAttribute("fr-FR" , UltimateResourceFallbackLocation.MainAssembly)]
[assembly: AssemblyTitleAttribute("WiiFlash Server")]
[assembly: AssemblyDescriptionAttribute("Wiimote for the Adobe Flash Platform")]
[assembly: AssemblyProductAttribute("WiiFlash Server")]
[assembly: AssemblyCopyrightAttribute("http://www.wiiflash.org")]
